### ISSUE TITLE
mistake

### ISSUE THREAD

**Issue by dannyid113** [Cl0udG0d/Fofa-hack#1]
Traceback (most recent call last):
  File "/notebooks/Fofa-hack/fofa.py", line 15, in <module>
    from lxml import etree
ImportError: cannot import name 'etree' from 'lxml' (/usr/lib/python3/dist-packages/lxml/__init__.py)

**Comment by Cl0udG0d** [comment]
等我加个部署教程，稍等

**Comment by Cl0udG0d** [comment]
已更新，请使用最新版本
![image](https://user-images.githubusercontent.com/45556496/211544292-d278423f-c248-4511-911a-1283c5c133b8.png)

**Comment by Cl0udG0d** [comment]
参考README文件安装运行所需的python 库

**Comment by dannyid113** [comment]
ok

**Comment by stripeboy** [comment]
现在貌似10页等待10秒都不行了
