### ISSUE TITLE
传入值跟实际搜索值不一样

### ISSUE THREAD

**Issue by fengzirock** [Cl0udG0d/Fofa-hack#13]
![image](https://user-images.githubusercontent.com/59859409/230576470-d236590e-a4e4-438d-8660-da2958c3ce89.png)
把两个等号吃掉了

**Comment by fengzirock** [comment]
![image](https://user-images.githubusercontent.com/59859409/230577006-df23afcc-b31e-4d7c-a33d-9d8bbef0cb6f.png)
![image](https://user-images.githubusercontent.com/59859409/230577065-5da3c3dc-6135-4c16-be6f-a3f49ccc12cb.png)
去掉了两个等号就没有数据 了

**Comment by Cl0udG0d** [comment]
首先Fofa-hack的原理是使用游客账号来进行访问fofa.info网站的，游客账号没有权限使用fid
![image](https://user-images.githubusercontent.com/45556496/230707850-00f291f1-8e31-46b6-88a5-5e77c5132686.png)

**Comment by Cl0udG0d** [comment]
搜索的关键词为 

fid="sSXXGNUO2FefBTcCLIT/2Q=="

**Comment by Cl0udG0d** [comment]
v2.1.4中已修复该问题 https://github.com/Cl0udG0d/Fofa-hack/releases/tag/v2.1.4

![image](https://user-images.githubusercontent.com/45556496/230708510-9bb55da2-b310-4be3-8d86-b0d625889445.png)

也就是等号被吃掉的问题解决了，然而游客权限无法使用指纹信息搜索是无法绕过的

**Comment by dannyid113** [comment]
how to add country
![捕获2](https://user-images.githubusercontent.com/97629264/230720310-c5230851-4351-49c9-b8bc-338472e9c899.PNG)
