### ISSUE TITLE
how to add country

### ISSUE THREAD

**Issue by dannyid113** [Cl0udG0d/Fofa-hack#15]
![捕获2](https://user-images.githubusercontent.com/97629264/230720345-60bc68e2-b830-4f50-be79-ba032de40854.PNG)

**Comment by Cl0udG0d** [comment]
这个是Fofa-hack为了最大化获取数据而进行的操作：

+ 当用户输入没有带 country 的关键字时，例如 host="edu.cn" ，Fofa-hack会自动进行 country 关键字的获取和多重遍历
+ 当用户输入带country的关键字时，例如 host="edu.cn" && counrty="AR" ，则会跳过上图的自动化country fuzz 部分

**Comment by stripeboy** [comment]
所以假如带country的关键字时详细指令是啥
