### ISSUE TITLE
使用高级语法查询发现结果为0

### ISSUE THREAD

**Issue by 1nformation** [Cl0udG0d/Fofa-hack#19]
![image](https://user-images.githubusercontent.com/93757156/236598238-f3300839-4854-4cc2-b438-251693f921df.png)

使用高级语法查询 结果为0。这个是正常的嘛

**Comment by Cl0udG0d** [comment]
这个是正常的，因为fofa-hack的原理导致它不支持fofa的高级语法

**Comment by Cl0udG0d** [comment]
这里的高级语法是指你这里使用的icon_hash以及其他需要登录才能使用的关键字
![image](https://user-images.githubusercontent.com/45556496/236598310-29722628-1a27-4511-acc7-b55b00ebe4c9.png)

**Comment by 1nformation** [comment]
谢谢，明白啦。

**Comment by Cl0udG0d** [comment]
刚才发现游客版本开放icon_hash的查询了

![image](https://github.com/Cl0udG0d/Fofa-hack/assets/45556496/940f03e7-733d-4337-be55-15c361d40e24)

![image](https://github.com/Cl0udG0d/Fofa-hack/assets/45556496/2e0046f3-7a9e-4221-8609-a5d6f588860a)
