### ISSUE TITLE
代码规范

### ISSUE THREAD

**Issue by Lejeremiah** [Cl0udG0d/Fofa-hack#20]
代码中既有camelCase又有 snake_case，函数功能和名称也有些不太符合。建议改善

**Comment by Cl0udG0d** [comment]
感谢提出的建议，在下一个小版本迭代中更正

**Comment by Cl0udG0d** [comment]
2.2.3
+ 除特殊变量外,变量统一命名规范为 小写字母+下划线
+ 除特殊方法外,方法一律使用小驼峰命名 camelCase
+ 方法名见名知意 复杂方法添加注释
+ 代码格式化
