### ISSUE TITLE
always error on level 2,3

### ISSUE THREAD

**Issue by tracyDevOps** [Cl0udG0d/Fofa-hack#22]
[-] error:list index out of range
[-] 1th attempt to get the page URL
[-] error:list index out of range
[-] 2th attempt to get the page URL
[-] error:list index out of range
[-] 3th attempt to get the page URL
[-] FOFA resource acquisition retries exceed the maximum number, and the program exits

on level 1 all fine .

**Comment by Cl0udG0d** [comment]
这个是BUG，将会在最近的更新中修复

**Comment by Cl0udG0d** [comment]
![image](https://github.com/Cl0udG0d/Fofa-hack/assets/45556496/3e0052a4-3de4-46cd-be41-9e7230604cda)
