### ISSUE TITLE
结果数量的问题

### ISSUE THREAD

**Issue by kafuuchino-s** [Cl0udG0d/Fofa-hack#24]
存在数量:29,307
爬取的话只能爬4千多，是每日只取前十个的问题是吗？

**Comment by Cl0udG0d** [comment]
我没有尝试过fofa-hack的极限，但是爬取4千多应该就是每日只取前十个导致的，等新版本更新吧，有一个新的想法

**Comment by Cl0udG0d** [comment]
如果你有什么好点子也可以联系我 :)

**Comment by kafuuchino-s** [comment]
> 如果你有什么好点子也可以联系我 :)

我看了下每页的个数可以增加至20个，所以我感觉可以改下pagesize=20，这样的话起码能翻倍了

**Comment by Cl0udG0d** [comment]
真的吗？游客状态的size最大应该就是10吧

**Comment by kafuuchino-s** [comment]
> 真的吗？游客状态的size最大应该就是10吧

是的，游客最大的size就是20
![image](https://github.com/Cl0udG0d/Fofa-hack/assets/51790568/3cb4dfd0-a48f-4fef-a1f1-49326bf4e48e)

https://api.fofa.info/v1/search
这个接口

**Comment by Cl0udG0d** [comment]
我明天看看，准备下班跑路了 :)

**Comment by Cl0udG0d** [comment]
我重新更新了代码 https://github.com/Cl0udG0d/Fofa-hack/releases/tag/v2.3.1

在2.3.1版本中新增了 --type 字段，我想你可以试试这个功能(虽然现在还不太稳定

利用selenium自动化注册和爬取，在登录状态能够查看前五页数据，与之同时带来的是一个月只有3000的额度，我觉得对于时间细粒度比较小的数据 在这个模式下应该会比较好

> python fofa.py -k index --type selenium

关于你说的游客获取最大size为20这个我会在下一个更新中加入common模式 tks~

**Comment by kafuuchino-s** [comment]
首先感谢你的更新，其次我认为既然都已经是自动化注册登录了，有了3000的额度，直接通过这个额度去下载一天的数据量，而不是去爬取前5页，这样的话一天最多可以爬3000个结果，用不完的顺延到下一天的结果，直至用完3000额度，继续注册爬取。请问我这种想法有机会实现吗？

**Comment by Cl0udG0d** [comment]
你重新注册一个fofa的账号，会发现只能访问前6页，应该是对个人版进行了限制
![image](https://github.com/Cl0udG0d/Fofa-hack/assets/45556496/4434a923-7f11-4e26-9c5e-e5d70d35bb2f)

所以我才没有这样处理

**Comment by Cl0udG0d** [comment]
orz 直接注册的账号没有f点啊，如果是讨论f点的话就没意义了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月2日(周五) 晚上10:50
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Cl0udG0d/Fofa-hack] 结果数量的问题 (Issue #24)




  
你重新注册一个fofa的账号，会发现只能访问前6页，应该是对个人版进行了限制 
 
所以我才没有这样处理
  
所以我直接用f点下载了2900个结果，前5页的话肯定没有这么多

**Comment by kafuuchino-s** [comment]
> orz 直接注册的账号没有f点啊，如果是讨论f点的话就没意义了
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年6月2日(周五) 晚上10:50 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [Cl0udG0d/Fofa-hack] 结果数量的问题 (Issue #24) 你重新注册一个fofa的账号，会发现只能访问前6页，应该是对个人版进行了限制 所以我才没有这样处理 所以我直接用f点下载了2900个结果，前5页的话肯定没有这么多 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

不好意思说错了，是免费额度那3000，我的意思是这额度开始是当f点用的，除去搜索，能直接下2990个结果，应该不止前5页的吧
![image](https://github.com/Cl0udG0d/Fofa-hack/assets/51790568/9b325a10-f88e-440d-a5a8-e193716592cd)

**Comment by Cl0udG0d** [comment]
哦看来还是我傻逼了

**Comment by Cl0udG0d** [comment]
可以实现，相当于是某一天最大的数据量为 2990，达到这个量之后就重新注册即可

**Comment by Cl0udG0d** [comment]
我周末有空就更新捏，最近还准备把微信群里面的机器人重新弄一下，欢迎加我微信

**Comment by kafuuchino-s** [comment]
> 可以实现，相当于是某一天最大的数据量为 2990，达到这个量之后就重新注册即可

是的，我的意思就是这样，然后如果数据量还大的话，就让用户自己细化搜索语法，多次搜索就行了。
这样的话就只要对导出的数据去下重就行，我还有个疑问就是，这样的话重复率会不会很高？会不会昨天有的结果，fofa今天还是扫到了，又加到今天的结果里面了？

**Comment by Cl0udG0d** [comment]
会有重复率很高的问题，但是我觉得这个去重不是问题，不管是在用户侧还是由fofa-hack来做都是很简单的

之前老版本的去重是对保存的文件读取出来在处理一遍，详情见 https://github.com/Cl0udG0d/Fofa-hack/commit/ae4a088b715778f0c7144b680f0486ea46c4ce1e
