### ISSUE TITLE
输出日志2.3错误

### ISSUE THREAD

**Issue by xx-super** [Cl0udG0d/Fofa-hack#26]
输出日志2和3都是这个错误
error:unhashable type: 'dict'

**Comment by Cl0udG0d** [comment]
跟这个[ISSUE](https://github.com/Cl0udG0d/Fofa-hack/issues/22) 一样 ，虽然也还没有修复 最近会修复它

**Comment by Cl0udG0d** [comment]
最新版本已解决该问题，请食用
