### ISSUE TITLE
REQ en Lange and proxy v2ray set

### ISSUE THREAD

**Issue by lolminerxmrig** [Cl0udG0d/Fofa-hack#27]
Hi.
plz add en Lange and proxy v2ray set.
thanks

**Comment by Cl0udG0d** [comment]
Okay, the English description will be updated in the next version, and the collection of V2 agents will not be considered for the time being, because I will focus on bypassing fofa

**Comment by lolminerxmrig** [comment]
and can easy import user pass or api.

**Comment by lolminerxmrig** [comment]
can make github code search very very need.

**Comment by Cl0udG0d** [comment]
Because of the current bypass mechanism of this program, he cannot use the user account

**Comment by Cl0udG0d** [comment]
Adding an English description makes it easier to search. Will foreigners also use fofa? :)

**Comment by Cl0udG0d** [comment]
Opening the API of this program will be the goal of the next stage

**Comment by Cl0udG0d** [comment]
a broken English readme is out
![image](https://github.com/Cl0udG0d/Fofa-hack/assets/45556496/92f43e4f-c786-43cd-bbe2-4b7adea458c5)

https://github.com/Cl0udG0d/Fofa-hack/blob/main/docs/EN_README.md

![image](https://github.com/Cl0udG0d/Fofa-hack/assets/45556496/0a36d4fa-abe6-4aed-819f-4051976e538b)

**Comment by lolminerxmrig** [comment]
thanks.
can add best code for search.
