### ISSUE TITLE
ddddocr cannot be piped

### ISSUE THREAD

**Issue by mmk6872** [Cl0udG0d/Fofa-hack#28]
pip3 install ddddocr
ModuleNotFoundError: No module named 'skbuild'

pip3 install skbuild
ERROR: No matching distribution found for skbuild

**Comment by Cl0udG0d** [comment]
请附加你使用的python版本

**Comment by mmk6872** [comment]
Python 3.6.8

**Comment by Cl0udG0d** [comment]
如图所示，我并没有出现你的问题
![image](https://github.com/Cl0udG0d/Fofa-hack/assets/45556496/93d144e0-ce31-4799-8626-2130e25a0e65)
安装库文件遇到啥问题查一下就行，虽然我没有遇到你这个报错，但是也遇到了其他的问题，最后也安装上了

**Comment by Cl0udG0d** [comment]
另外可以用现在的release版本 https://github.com/Cl0udG0d/Fofa-hack/releases/tag/v2.3.5，直接运行exe即可，不用安装环境
