### ISSUE TITLE
师傅好

### ISSUE THREAD

**Issue by hackerissb** [Cl0udG0d/Fofa-hack#29]
我是普通会员，可以不限制浏览，我想要用我自己的cookie爬取，请问修改哪部分

**Comment by Cl0udG0d** [comment]
普通会员，普通还是会员

**Comment by Cl0udG0d** [comment]
没有账号能够不限制浏览 就算你是会员也有一万条的限制

**Comment by hackerissb** [comment]
就是一万条的那个

发自我的iPhone

**Comment by Cl0udG0d** [comment]
现在这个是无账号的，如果你有会员 建议去用其他人的fofa采集工具，或者等我更新这个功能

**Comment by hackerissb** [comment]
好的师傅

**Comment by Cl0udG0d** [comment]
> 大师，为什么
> 
> > 现在这个是无账号的，如果你有会员 建议去用其他人的fofa采集工具，或者等我更新这个功能
> 
> 大师，为什么在web界面搜索显示有9000多条，实际用你的工具只有2700多就结束爬取了，提示0条数据枯竭后程序退出。开始我以为是网络不稳定中断了，实测好几个搜索条件都是如此，

鱼和熊掌不可兼得，长时间爬取之后退出的原因有多种，比如FOFA本身的爬虫制裁机制，时间戳到了终点等等

如果fofa-hack能够完完全全爬取所有的fofa搜索结果，我觉得第二天我就收到律师函了 :)

**Comment by Cl0udG0d** [comment]
> 我是普通会员，可以不限制浏览，我想要用我自己的cookie爬取，请问修改哪部分

新增了--authorization 参数

![image](https://github.com/Cl0udG0d/Fofa-hack/assets/45556496/644f6664-53fa-4871-803d-c1fd3bc1bb81)

作为会员的你可以通过F12获取到自己的 authorization ，如图

![image](https://github.com/Cl0udG0d/Fofa-hack/assets/45556496/f6a80bff-0595-489a-8207-cc23254fc9db)

通过指定authorization来获取数据

> fofa-hack_win_amd64.exe -k thinkphp --authorization 你的authorization

![image](https://github.com/Cl0udG0d/Fofa-hack/assets/45556496/5255867f-2f97-473e-8cdd-6bd41544dcab)

但是fofa对于authorization来获取数据感觉也存在一些爬虫限制，获取的结果并不完美
