### ISSUE TITLE
如何接着上一次的获取IP再往下走呢？

### ISSUE THREAD

**Issue by safe-b** [Cl0udG0d/Fofa-hack#30]
比如我这次获取xx管理系统 500条
下一次我想或许501~1000之间的500条

**Comment by Cl0udG0d** [comment]
建议还是一起采集了，fofa-hack内置了去重，因为每次搜索的时候fofa返回的结果其实是有一点不可控的，就像是你在网页端搜索两次fofa同一个关键字，出来的结果数量可能是相同的，但是顺序是不一致的

**Comment by safe-b** [comment]
因为有时候数据挺多的。一次性采集中间可能会断。

**Comment by Cl0udG0d** [comment]
目前还没有比较好的解决办法，可以考虑自己细分一下搜索关键字 比如过滤一下各个地区之类的
