### ISSUE TITLE
city, asn, organization Always Empty on level 3

### ISSUE THREAD

**Issue by kontorol** [Cl0udG0d/Fofa-hack#34]
'city': '', 'asn': '', 'organization': ''

Always Empty on level 3 (city mostly)

_Originally posted by @kontorol in https://github.com/Cl0udG0d/Fofa-hack/issues/22#issuecomment-1656840955_

**Comment by Cl0udG0d** [comment]
Use version 2.3.6 to solve this problem

https://github.com/Cl0udG0d/Fofa-hack/releases/tag/v2.3.6


![image](https://github.com/Cl0udG0d/Fofa-hack/assets/45556496/0c511c5e-a1be-4507-ba06-b57e8ee5459c)
