### ISSUE TITLE
"unhashable type: 'dict'" in json output

### ISSUE THREAD

**Issue by kontorol** [Cl0udG0d/Fofa-hack#36]
[-] error:unhashable type: 'dict'
[-] 第3次尝试获取页面URL
[-] FOFA资源获取重试超过最大次数,程序退出

**Comment by Cl0udG0d** [comment]
能把具体的运行指令发出来吗

**Comment by Cl0udG0d** [comment]
这个问题应该是 -k index -l 2 -o json 这种情况下会出现的

![42a56adf35689a02aa99dd31864a16b](https://github.com/Cl0udG0d/Fofa-hack/assets/45556496/c46e45ad-e4e0-435d-a4d2-808fdf21d6b3)

在[最新版本2.3.8](https://github.com/Cl0udG0d/Fofa-hack/releases/tag/v2.3.8) 里面修复了该问题
