### ISSUE TITLE
search_key

### ISSUE THREAD

**Issue by RDPLinux** [Cl0udG0d/Fofa-hack#39]
[-] error:list index out of range
[*] ????:0
now search key: "man"
[*] ????? [0]: []
Traceback (most recent call last):
  File "fofa.py", line 64, in <module>
    main()
  File "fofa.py", line 60, in main
    fofa.start()
  File "/root/Fofa-hack/core/fofaC.py", line 511, in start
    self.fofaSpider(self.search_key, searchbs64, 0)
  File "/root/Fofa-hack/core/fofaC.py", line 329, in fofaSpider
    search_key_modify = self.modifySearchTimeUrl(search_key, index)
  File "/root/Fofa-hack/core/fofaC.py", line 431, in modifySearchTimeUrl
    time_first = timestamp_list[0].split(' ')[0].strip('\n').strip()
IndexError: list index out of range

Any Search that gives me the same message, may you check and update, please.

**Comment by RDPLinux** [comment]
[*] LEVEL = 1 , 初始化成功
[*] 爬取延时: 3s
[*] 爬取关键字: "thinkphp"
[*] 爬取结束数量: 100
[*] 输出格式为: txt
[*] 存储文件名: facc36ec160014e8e39a4bf2c3736e1f_1691989175.txt
[*] 是否开启关键字fuzz: False
[*] 是否开启代理: False
[*] 不从文件中读取

[*] 开始运行
[*] 爬取页面为:https://fofa.info/result?qbase64=InRoaW5rcGhwIg==
[-] error:list index out of range
[*] 存在数量:0
无搜索结果
[*] 抓取结束，共抓取数据 0 条

**Comment by Cl0udG0d** [comment]
Please provide your search command and usage version

My command is

> fofa-hack.exe -k thinkphp

It seems to be running smoothly

![image](https://github.com/Cl0udG0d/Fofa-hack/assets/45556496/d21e83af-1769-4d4c-bcdd-20ebac1887ce)

**Comment by RDPLinux** [comment]
V 2.3.6
python3 fofa.py -k "Test" --output Test

https://prnt.sc/vojpWS3KYGSk

**Comment by Cl0udG0d** [comment]
No output parameter is Test

**Comment by RDPLinux** [comment]
Hi
I already use V 2.3.6 and use the command correctly, but I still have the same problem.

This problem occurred on 3 Linux servers and on Windows Server  using Python 3.


https://prnt.sc/b_-Efmqp4Cyl

[-] error:list index out of range
[*] 存在数量:0
无搜索结果
[*] 抓取结束，共抓取数据 0 条

**Comment by Cl0udG0d** [comment]
Is your server not within China

**Comment by Cl0udG0d** [comment]
I suspect it's a network issue

**Comment by xx-super** [comment]
我也出现这个问题了，昨天都还好的

**Comment by Cl0udG0d** [comment]
> 我也出现这个问题了，昨天都还好的

你用的exe还是python文件，版本是多少 我这边还是没有复现这个问题

**Comment by Cl0udG0d** [comment]
> Hi The script was working fine, then stopped working, so it's not about the server from China or not. also I installed the code in 3 Linux Servers locations, and the issue is still the same. Please test from your said maybe you can find the issue and solve it.

![image](https://github.com/Cl0udG0d/Fofa-hack/assets/45556496/f897236e-9bf5-429f-b09b-e021d0fcae8c)

Do you have a curl tool on your server? Perhaps you can use it to troubleshoot the problem and tell me the curl results

> curl https://fofa.info/result?qbase64=IlRlc3Qi

**Comment by RDPLinux** [comment]
https://prnt.sc/uPZ7AEIk29fz
Please Check

**Comment by RDPLinux** [comment]
to be sure that my network has not been blocked from FOFA.
This is a ping test.
Working fine 
PING fofa.info (101.36.123.64) 56(84) bytes of data.
64 bytes from 101.36.123.64 (101.36.123.64): icmp_seq=1 ttl=39 time=167 ms
64 bytes from 101.36.123.64 (101.36.123.64): icmp_seq=2 ttl=39 time=167 ms
64 bytes from 101.36.123.64 (101.36.123.64): icmp_seq=3 ttl=39 time=167 ms
64 bytes from 101.36.123.64 (101.36.123.64): icmp_seq=4 ttl=39 time=167 ms
^C
--- fofa.info ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3003ms
rtt min/avg/max/mdev = 167.524/167.552/167.596/0.502 ms

**Comment by RDPLinux** [comment]
[-] Error: list index out of range I think this error is due to the script not calculating the number typed in the search, so it gets no results to download.
Also, I know how your idea for coding this script is to create an account in Fofa using a temporary email, then get the active code that was sent from Fofa, then use it to download the free quota, then create another account, etc. and really it's a good idea, but If you will update the version, please add the tor option for every process for auto-reload and change the IP address to avoid being blocked because tor is free and better than Proxy . 


[*] LEVEL = 1 , åˆå§‹åŒ–æˆåŠŸ
[*] çˆ¬å–å»¶æ—¶: 3s
[*] çˆ¬å–å…³é”®å­—: "index"
[*] çˆ¬å–ç»“æŸæ•°é‡: 100
[*] è¾“å‡ºæ ¼å¼ä¸º: txt
[*] å­˜å‚¨æ–‡ä»¶å: 29d21d3a0b2470eea8228514d74cd213_1692267387.txt
[*] æ˜¯å¦å¼€å¯å…³é”®å­—fuzz: False
[*] æ˜¯å¦å¼€å¯ä»£ç†: False
[*] ä¸ä»Žæ–‡ä»¶ä¸­è¯»å–

[*] å¼€å§‹è¿è¡Œ
[*] çˆ¬å–é¡µé¢ä¸º:https://fofa.info/result?qbase64=ImluZGV4Ig==
[-] error:list index out of range
[*] å­˜åœ¨æ•°é‡:0
æ— æœç´¢ç»“æžœ
[*] æŠ“å–ç»“æŸï¼Œå…±æŠ“å–æ•°æ® 0 æ¡

**Comment by Cl0udG0d** [comment]
> [-] Error: list index out of range I think this error is due to the script not calculating the number typed in the search, so it gets no results to download. Also, I know how your idea for coding this script is to create an account in Fofa using a temporary email, then get the active code that was sent from Fofa, then use it to download the free quota, then create another account, etc. and really it's a good idea, but If you will update the version, please add the tor option for every process for auto-reload and change the IP address to avoid being blocked because tor is free and better than Proxy .
> 
> [_] LEVEL = 1 , åˆ�å§‹åŒ–æˆ�åŠŸ [_] çˆ¬å�–å»¶æ—¶: 3s [_] çˆ¬å�–å…³é”®å­—: "index" [_] çˆ¬å�–ç»“æ�Ÿæ•°é‡�: 100 [_] è¾“å‡ºæ ¼å¼�ä¸º: txt [_] å­˜å‚¨æ–‡ä»¶å��: 29d21d3a0b2470eea8228514d74cd213_1692267387.txt [_] æ˜¯å�¦å¼€å�¯å…³é”®å­—fuzz: False [_] æ˜¯å�¦å¼€å�¯ä»£ç�†: False [*] ä¸�ä»Žæ–‡ä»¶ä¸­è¯»å�–
> 
> [_] å¼€å§‹è¿�è¡Œ [_] çˆ¬å�–é¡µé�¢ä¸º:https://fofa.info/result?qbase64=ImluZGV4Ig== [-] error:list index out of range [_] å­˜åœ¨æ•°é‡�:0 æ— æ�œç´¢ç»“æžœ [_] æŠ“å�–ç»“æ�Ÿï¼Œå…±æŠ“å�–æ•°æ�® 0 æ�¡

I'm sorry you misunderstood. The method you mentioned is not the default search method. In fact, Fofa hack uses timestamps to infinitely crawl results

**Comment by Cl0udG0d** [comment]
> https://prnt.sc/uPZ7AEIk29fz Please Check

It seems that your IP cannot access this website address https://fofa.info/result?qbase64=IlRlc3Qi

Here are my results

![image](https://github.com/Cl0udG0d/Fofa-hack/assets/45556496/d56eda9b-6eb4-419a-b829-f96b919c8165)

There is still a lot of content to follow, such as

![image](https://github.com/Cl0udG0d/Fofa-hack/assets/45556496/e09b4be8-1c20-4166-80f2-faeec533956b)

You can check if there are any keywords in your curl results "Certificate Signature Algorithm"

use 

> curl https://fofa.info/result?qbase64=IlRlc3Qi | findstr "Certificate Signature Algorithm"

or use 

> curl https://fofa.info/result?qbase64=IlRlc3Qi | grep "Certificate Signature Algorithm"

You can see that this is

![image](https://github.com/Cl0udG0d/Fofa-hack/assets/45556496/86aeeed9-f50e-47ac-a537-544a4eb5265b)

**Comment by RDPLinux** [comment]
Hi
The issue has been solved after using a China proxy.

**Comment by Cl0udG0d** [comment]
Okay, it seems that Fofa's company has blocked access to overseas servers

**Comment by Yakui420** [comment]
> Okay, it seems that Fofa's company has blocked access to overseas servers

This example domain breaks for all overseas people:
https://fofa.info/result?qbase64=IlRlc3Qi
![Image](https://github.com/user-attachments/assets/3ad2e467-0f2f-407b-8431-abc6a550c827)

The standard fofa.info domain seems to be explicitly for chinese users only. 
The way how to easily fix this is to add `en.` before the fofa domain for all overseas users.

https://en.fofa.info/result?qbase64=IlRlc3Qi
Now it works and I don't get an error message anymore. No need for Chinese proxies.
Would be nice if you could fix this in the newer versions.
