### ISSUE TITLE
Seems like it's not working

### ISSUE THREAD

**Issue by fatmeat** [Cl0udG0d/Fofa-hack#40]
I can search in the web portal but the python script just show error "error:list index out of range"

             ____  ____  ____  ____
            | ===|/ () \| ===|/ () \
            |__|  \____/|__| /__/\__\
                 _   _   ____   ____  __  __
                | |_| | / () \ / (__`|  |/  /
                |_| |_|/__/\__\\____)|__|\__\ V2.3.6

                公众号: 黑糖安全

[*] LEVEL = 1 , 初始化成功
[*] 爬取延时: 3s
[*] 爬取关键字: "thinkphp"
[*] 爬取结束数量: 100
[*] 输出格式为: txt
[*] 存储文件名: facc36ec160014e8e39a4bf2c3736e1f_1692280744.txt
[*] 是否开启关键字fuzz: False
[*] 是否开启代理: False
[*] 不从文件中读取

[*] 开始运行
[*] 爬取页面为:https://fofa.info/result?qbase64=InRoaW5rcGhwIg==
[-] error:list index out of range
[*] 存在数量:0
无搜索结果
[*] 抓取结束，共抓取数据 0 条

**Comment by Cl0udG0d** [comment]
You can refer to this [ISSUE](https://github.com/Cl0udG0d/Fofa-hack/issues/39)

**Comment by xx-super** [comment]
好了，国外服务器今天又可以了

**Comment by Cl0udG0d** [comment]
现在还没搞懂fofa屏蔽的规则 orz

**Comment by Cl0udG0d** [comment]
> I think that the reason is too much use of your code. This is why they provided protection two days ago. As I remember, the FOFA website was closed for 5 minutes, then a protection system was added to block foreign servers. But, you know, I don't understand how they did it.
> 
> From USA IP, you can browse their website, but it is not working through your code. From the same IP When you run the code
> 
> You should expect anything from any company that wants to protect their site
> 
> As you know, they sell products, but their prices are very expensive, so you did a good job when you created this code.

Thank you for liking this project. I think I will continue to update it
