### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by lolminerxmrig** [Cl0udG0d/Fofa-hack#41]
Hi.
plz can help fixed Error:

←[1;32m[*] LEVEL = 1 , 初始化成功
[*] 爬取延时: 3s
[*] 爬取关键字: app="JupyterHub" && fid="S5PclJWyDGGHYSTiauu9VA=="
[*] 爬取结束数量: 10000
[*] 输出格式为: txt
[*] 存储文件名: 5877ffe04d1197cfaecd7ebef3eafc24_1692523465.txt
[*] 是否开启关键字fuzz: False
[*] 是否开启代理: False
[*] 不从文件中读取
←[0m
←[1;32m[*] 开始运行←[0m
←[1;32m[*] 爬取页面为:https://fofa.info/result?qbase64=YXBwPSJKdXB5dGVySHViIiAmJiBmaWQ9IlM1UGNsSld5REdHSFlTVGlhdXU5VkE9PSI=←[0m
←[1;31m[-] error:list index out of range←[0m
←[1;32m[*] 存在数量:0←[0m
无搜索结果
←[1;32m[*] 抓取结束，共抓取数据 ←[1;33m0 ←[1;32m条←[0m

**Comment by Cl0udG0d** [comment]
This issue is not caused by the program. Fofa's tourist status does not support searching for fid

![image](https://github.com/Cl0udG0d/Fofa-hack/assets/45556496/444e01eb-cc17-49ec-919b-b403f81b0ff4)

**Comment by lolminerxmrig** [comment]
show for me :

![image](https://github.com/Cl0udG0d/Fofa-hack/assets/108659226/11f03bcf-c4a4-4a7f-bfc4-9558f80dd8ba)

**Comment by Cl0udG0d** [comment]
When you took the screenshot, it should be in login status, while fofa back is not logged in status
