### ISSUE TITLE
只能抓取一天的资源吗

### ISSUE THREAD

**Issue by Chalkbro** [Cl0udG0d/Fofa-hack#42]
![捕获](https://github.com/Cl0udG0d/Fofa-hack/assets/105379301/38bebe3e-7408-447c-abd6-164ab9063683)

**Comment by Cl0udG0d** [comment]
FOFA游客状态下只能访问一页数据，所以在fofa-hack里面的显示是一天的，如果你觉得按天的话漏掉的数据太多了，可以考虑添加参数 -f

例如
> fofa-hack_win_amd64.exe -k index -f

![image](https://github.com/Cl0udG0d/Fofa-hack/assets/45556496/2072e941-0fa1-4df1-b94a-5d2d95f54ab5)
