### ISSUE TITLE
爬取条数问题

### ISSUE THREAD

**Issue by aHlo666** [Cl0udG0d/Fofa-hack#43]
指定--endcount 1000，但实际上只有100多条数据，这样运行就会报错，最后也不会生成final_*_.txt文件
![image](https://github.com/Cl0udG0d/Fofa-hack/assets/67671500/45bf7a2f-692e-48ca-ba3d-f817f7be65a1)

**Comment by Cl0udG0d** [comment]
--endcount 1000 ，最后停止的节点其实是不可控的，因为对于fofa来说对于某个特征的关键字可能就只有十天的时间戳，例如 2023-8-21到2023-8-11，在2023-8-11之前的时间就没有了，所以在这里就强制退出了

对于第二个报错的问题，确实这部分的退出比较暴力 在下一个版本里面对时间戳退出进行优化

对于第三个生成文件问题，同上，下次更新 :)

**Comment by Cl0udG0d** [comment]
可以把查询的关键字发给我吗，我修改之后进行本地测试一下

**Comment by TibbersV6** [comment]
![image](https://github.com/Cl0udG0d/Fofa-hack/assets/117791583/befc4cc4-9a39-461e-bb29-9be9ee218128)

**Comment by Cl0udG0d** [comment]
运行的命令如果不发的话 我脑补不出来是咋运行的


> ![image](https://user-images.githubusercontent.com/117791583/266492166-befc4cc4-9a39-461e-bb29-9be9ee218128.png)

**Comment by aHlo666** [comment]
> 可以把查询的关键字发给我吗，我修改之后进行本地测试一下

举个例子，比如菜鸟教程网站域名只有26条结果，指定爬取100条
./fofa-hack_linux_amd64 -k "domain='runoob.com'" -e 100
![image](https://github.com/Cl0udG0d/Fofa-hack/assets/67671500/76bfba2d-0517-49d9-90db-0b5a760d10c2)
最后就会报这个错误
![image](https://github.com/Cl0udG0d/Fofa-hack/assets/67671500/399fac34-ded8-4b6a-b51e-bc6dc24c0776)

**Comment by Cl0udG0d** [comment]
使用[最新版本 v2.3.9](https://github.com/Cl0udG0d/Fofa-hack/releases/tag/v2.3.9)

> 指定--endcount 1000，但实际上只有100多条数据

这个问题是由fofa-hack的机制决定的，可以尝试添加 --fuzz 参数

在最新版本中，如果时间戳导致停止的时候，不再会产生报错，并且会生成final_*_.txt文件了
