### ISSUE TITLE
Linux Error

### ISSUE THREAD

**Issue by lolminerxmrig** [Cl0udG0d/Fofa-hack#44]
Hi.
plz help me fixed Error :
Traceback (most recent call last):
  File "fofa.py", line 66, in <module>
    main()
  File "fofa.py", line 21, in main
    outputLogo()
  File "/root/Desktop/fofa/Fofa-hack-2.3.7/tookit/unit.py", line 33, in outputLogo
    '''.format(config.VERSION_NUM))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 318-320: ordinal not in range(128)

**Comment by Cl0udG0d** [comment]
I ran the `./fofa -h` command on the ubuntu server without any character issues

![image](https://github.com/Cl0udG0d/Fofa-hack/assets/45556496/35fa13d8-6adb-4f11-8481-19bc9f90005f)

**Comment by Cl0udG0d** [comment]
You can directly download the release version instead of running the code

https://github.com/Cl0udG0d/Fofa-hack/releases/tag/v2.3.8

![image](https://github.com/Cl0udG0d/Fofa-hack/assets/45556496/6997a504-0e2d-4a61-95fc-031d64e72f12)
