### ISSUE TITLE
Error 2.3.9

### ISSUE THREAD

**Issue by lolminerxmrig** [Cl0udG0d/Fofa-hack#45]
Hi.
plz help for fixed Error:

fofa.py --keyword title=="Directory listing for /" --endcount 10000
←[1;32m
             ____  ____  ____  ____
            | ===|/ () \| ===|/ () \
            |__|  \____/|__| /__/\__\
                 _   _   ____   ____  __  __
                | |_| | / () \ / (__`|  |/  /
                |_| |_|/__/\__\\____)|__|\__\ ←[0m←[1;34mV2.3.9←[0m

                ←[1;32m公众号: 黑糖安全←[0m

←[1;32m[*] LEVEL = 1 , 初始化成功
[*] 爬取延时: 3s
[*] 爬取关键字: title==Directory listing for /
[*] 爬取结束数量: 10000
[*] 输出格式为: txt
[*] 存储文件名: 9d5009ede0ef808a5aae05a9ffab9994_1694680643.txt
[*] 是否开启关键字fuzz: False
[*] 是否开启代理: False
[*] 不从文件中读取
←[0m
←[1;32m[*] 开始运行←[0m
←[1;32m[*] 爬取页面为:https://fofa.info/result?qbase64=dGl0bGU9PURpcmVjdG9yeSBsaXN0aW5nIGZvciAv←[0m
←[1;32m[*] 存在数量:0←[0m
无搜索结果
←[1;32m[*] 抓取结束，共抓取数据 ←[1;33m0 ←[1;32m条←[0m

**Comment by Cl0udG0d** [comment]
This is a problem with FOFA parsing, and I need to modify this part of the code

**Comment by Cl0udG0d** [comment]
After reviewing the issue with your keyword, you can try the following keyword

> -k "title=='Directory listing for /'"

![image](https://github.com/Cl0udG0d/Fofa-hack/assets/45556496/83066ab8-5dab-4f42-ae00-7a6b3a6789da)
