### ISSUE TITLE
能爬的动10w条以上的数据吗  :)

### ISSUE THREAD

**Issue by MisakaSama111** [Cl0udG0d/Fofa-hack#46]
rt

**Comment by Cl0udG0d** [comment]
我以为我回了邮件会同步到github orz

**Comment by Cl0udG0d** [comment]
理论上可以，实际上因为网络情况、fofa自身的检测拦截，其实很难获取到10w条这么多数据

如果需要这么多数据，建议还是使用官方api花钱下载
