### ISSUE TITLE
REQ Add En language

### ISSUE THREAD

**Issue by lolminerxmrig** [Cl0udG0d/Fofa-hack#47]
Hi
plz add en language

![image](https://github.com/Cl0udG0d/Fofa-hack/assets/108659226/566d004a-0eef-4b40-90d8-8b988e55d16b)

**Comment by Cl0udG0d** [comment]
Waiting for me to update

**Comment by lolminerxmrig** [comment]
thanks a lot.
me update but not work : 
https://twitter.com/fofabot/status/1714272553542541567

body="<script>window.onload=function(){ url ='/webui';window.location.href=url;}</script>"

**Comment by Cl0udG0d** [comment]
I think it's because the search parameters are too complex, with too many single and double quotes. I need to reset the input of the parameters

**Comment by Cl0udG0d** [comment]
Updated to use base64 value as keyword, use -b, use latest version [2.4.3](https://github.com/Cl0udG0d/Fofa-hack/releases/tag/v2.4.3)

**keywords ：** body="<script>window.onload=function(){ url ='/webui';window.location.href=url;}</script>"

**base64:** Ym9keT0iPHNjcmlwdD53aW5kb3cub25sb2FkPWZ1bmN0aW9uKCl7IHVybCA9Jy93ZWJ1aSc7d2luZG93LmxvY2F0aW9uLmhyZWY9dXJsO308L3NjcmlwdD4i

use 
> .\fofa-hack_win_amd64.exe -b Ym9keT0iPHNjcmlwdD53aW5kb3cub25sb2FkPWZ1bmN0aW9uKCl7IHVybCA9Jy93ZWJ1aSc7d2luZG93LmxvY2F0aW9uLmhyZWY9dXJsO308L3NjcmlwdD4i

![image](https://github.com/Cl0udG0d/Fofa-hack/assets/45556496/a32ed370-6557-40b3-9178-1d3c758a7ced)

**Comment by Cl0udG0d** [comment]
Use the -b or --base argument

**Comment by lolminerxmrig** [comment]
can change url?
en.fofa

**Comment by Cl0udG0d** [comment]
Currently there is no support for changing the URL to en.fofa, the actual address of the URL to get data is still api.fofa.info, there is no difference, so I don't think there is a need to change it

![image](https://github.com/Cl0udG0d/Fofa-hack/assets/45556496/cb4b81e4-bb3f-4ed8-bedb-3eb805573a51)
