### ISSUE TITLE
[-] error:list index out of range

### ISSUE THREAD

**Issue by lolminerxmrig** [Cl0udG0d/Fofa-hack#48]
hi 
me try code but send error

./fofa-hack_linux_amd64.1 --keyword "icon_hash='945408572' && fid='YN8TQbvCRB8YHhecCBOapQ=='" --endcount 10000

icon_hash="945408572" && fid="YN8TQbvCRB8YHhecCBOapQ=="

![image](https://github.com/Cl0udG0d/Fofa-hack/assets/108659226/84e2270d-69a2-46b5-9315-90b24ab6fa1f)

**Comment by Cl0udG0d** [comment]
The fid keyword is not supported

![image](https://github.com/Cl0udG0d/Fofa-hack/assets/45556496/90ddeb00-8178-49d1-997a-32be4b225534)

**Comment by Cl0udG0d** [comment]
You can enter content in the search box of Fofa to test it

> icon_hash="945408572" && fid="YN8TQbvCRB8YHhecCBOapQ=="

**Comment by lolminerxmrig** [comment]
app:"Confluence"

![image](https://github.com/Cl0udG0d/Fofa-hack/assets/108659226/eeb54f1e-86e9-44f4-bb25-cff19ca4c2fa)

**Comment by lolminerxmrig** [comment]
over and over send me Error.

**Comment by lolminerxmrig** [comment]
> You can enter content in the search box of Fofa to test it
> 
> > icon_hash="945408572" && fid="YN8TQbvCRB8YHhecCBOapQ=="

en.fofa yes.

**Comment by Cl0udG0d** [comment]
> > You can enter content in the search box of Fofa to test it
> > > icon_hash="945408572" && fid="YN8TQbvCRB8YHhecCBOapQ=="
> 
> en.fofa yes.

Really? Please send me the website where your search was successful

**Comment by Cl0udG0d** [comment]
> app:"Confluence"

Search syntax error

You can give it a try

> app="ATLASSIAN-Confluence"

**Comment by Cl0udG0d** [comment]
When the syntax you search for is correct, you can obtain results

![image](https://github.com/Cl0udG0d/Fofa-hack/assets/45556496/1a2e8078-1adc-49dc-b030-802ec0a755a1)
