### ISSUE TITLE
string indices must be integers

### ISSUE THREAD

**Issue by chendi2** [Cl0udG0d/Fofa-hack#51]
![image](https://github.com/Cl0udG0d/Fofa-hack/assets/55273217/aecf4354-4888-4eca-bf4c-11a3ff7b3010)
出现报错：string indices must be integers

**Comment by chendi2** [comment]
req为None，返回值为：{"code":820000,"message":"[820000] 查询语法错误","data":""}

**Comment by Cl0udG0d** [comment]
关键字方便发出来吗

**Comment by chendi2** [comment]
> 关键字方便发出来吗

发你公众号了，大佬

**Comment by Cl0udG0d** [comment]
看起来是一个BUG 新版本修复

**Comment by chendi2** [comment]
> 看起来是一个BUG 新版本修复

应该是拼接的URL有问题，

**Comment by Cl0udG0d** [comment]
使用新版本 [Fofa-hack v2.4.5](https://github.com/Cl0udG0d/Fofa-hack/releases/tag/v2.4.5)

该问题已解决，输入的关键字处理的问题

**Comment by chendi2** [comment]
验证修复，辛苦作者大大

**Comment by Cl0udG0d** [comment]
it's my pleasure.
