### ISSUE TITLE
BUG?

### ISSUE THREAD

**Issue by aniusang** [Cl0udG0d/Fofa-hack#53]
当指定level为2或者为3时出错如下
<img width="218" alt="屏幕截图 2023-10-26 150221" src="https://github.com/Cl0udG0d/Fofa-hack/assets/113170328/913a1855-4bdb-4766-a75b-60fa3cfaaef9">
<img width="755" alt="屏幕截图 2023-10-26 150254" src="https://github.com/Cl0udG0d/Fofa-hack/assets/113170328/863ebc3b-dc14-4cba-80e7-9f9b3aa2eeb0">
<img width="213" alt="屏幕截图 2023-10-26 150342" src="https://github.com/Cl0udG0d/Fofa-hack/assets/113170328/bd61b062-7c09-45ac-b1bf-0e7f2b35891a">
<img width="308" alt="屏幕截图 2023-10-26 150421" src="https://github.com/Cl0udG0d/Fofa-hack/assets/113170328/1380d496-73ad-407a-9ea2-1568b813e50d">

**Comment by Cl0udG0d** [comment]
是的，先不使用level参数吧，这个问题新版本修复

**Comment by Cl0udG0d** [comment]
使用新版本 [Fofa-hack v2.4.5](https://github.com/Cl0udG0d/Fofa-hack/releases/tag/v2.4.5)

level 参数问题已解决

![image](https://github.com/Cl0udG0d/Fofa-hack/assets/45556496/b2993a5e-7c8c-47f5-b063-578d04acea78)
