### ISSUE TITLE
fofa爬下来的数据存在https://****.com****.au这种情况

### ISSUE THREAD

**Issue by black9527233** [Cl0udG0d/Fofa-hack#57]
![1](https://github.com/Cl0udG0d/Fofa-hack/assets/152794996/58e6d2a6-dc57-431a-b5d8-1b283619e5bf)

**Comment by Cl0udG0d** [comment]
这是fofa在国内为了过合规进行的操作，这种数据在网页上你也是看不到的

例如你输入关键字 "棋牌"

![image](https://github.com/Cl0udG0d/Fofa-hack/assets/45556496/996e62e4-f7fa-42b2-b62b-61f7a309456d)

可以看到这里的数据看不到
