### ISSUE TITLE
error:'NoneType' object has no attribute 'text'

### ISSUE THREAD

**Issue by trasurc** [Cl0udG0d/Fofa-hack#59]
now search key: body="中文" && country="CN" && region!="HK" && region!="MO" && before="2023-12-15"
string indices must be integers
[-] error:'NoneType' object has no attribute 'text'
[-] 第1次尝试获取页面URL
string indices must be integers
[-] error:'NoneType' object has no attribute 'text'
[-] 第2次尝试获取页面URL
string indices must be integers
[-] error:'NoneType' object has no attribute 'text'
[-] 第3次尝试获取页面URL
[-] FOFA资源获取重试超过最大次数,程序退出

body="中文"   中文就会出错
version 2.4.9

**Comment by Cl0udG0d** [comment]
真的会出现这个问题吗 

我使用[v2.4.9](https://github.com/Cl0udG0d/Fofa-hack/releases/tag/v2.4.9)并没有出现这个问题

运行命令为 
> .\fofa-hack_win_amd64.exe -k "body='中文' && country='CN' && region!='HK' && region!='MO' && before='2023-12-15'"

![image](https://github.com/Cl0udG0d/Fofa-hack/assets/45556496/e08a8895-6fb5-47f0-b8bf-071d97ef936b)

**Comment by trasurc** [comment]
keyword换成这个就不行了 
fofa-hack_win_amd64.exe -k "body='亿邮邮件' && country='CN' && region!='HK' && region!='MO'" -e 1000

**Comment by Cl0udG0d** [comment]
已复现 等我检查一下再更新 
![image](https://github.com/Cl0udG0d/Fofa-hack/assets/45556496/6ef49f33-8607-4301-a06f-464dbeeeb96d)

**Comment by trasurc** [comment]
感谢。

**Comment by Cl0udG0d** [comment]
使用最新版本试试 https://github.com/Cl0udG0d/Fofa-hack/releases/tag/v2.4.10

![image](https://github.com/Cl0udG0d/Fofa-hack/assets/45556496/fcc52fce-1a87-460d-bad6-8f52932c6142)

**Comment by trasurc** [comment]
2.4.10没问题，辛苦了。
