### ISSUE TITLE
Error : Keyword: product=

### ISSUE THREAD

**Issue by lolminerxmrig** [Cl0udG0d/Fofa-hack#60]
[*] LEVEL = 1 ，Initialized Successfully
[*] Crawling Delay: 3s
[*] Crawling Keyword: product="ATLASSIAN-Confluence"
[*] Crawling Result Count: 2000
[*] Output Format: At.txt
[*] Storage File Name: fofaHack.At.txt
[*] Enable Keyword Fuzzing: False
[*] Enable Proxy: False
[*] Reading File: None
[*] Commencement of operations
[*] Crawl page for:https://fofa.info/result?qbase64=cHJvZHVjdD0iQVRMQVNTSUFOLUNvbmZsdWVuY2Ui
[-] error:list index out of range
Perhaps there is a problem with your network or your area has been officially banned by Fofa, so the program exits
Traceback (most recent call last):
  File "C:\Fofa-hack\Fofa-hack-2.4.10\Fofa-hack-2.4.10\core\fofaMain.py", line 121, in getFofaKeywordsCount
    countnum = tree.xpath('//span[@class="hsxa-highlight-color"]/text()')[0]
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^

**Comment by Cl0udG0d** [comment]
The search keyword product requires a login, in which case fofa-hack cannot be used.

![image](https://github.com/Cl0udG0d/Fofa-hack/assets/45556496/d4e9eff5-5bd8-487a-b992-16f87f37805c)
