### ISSUE TITLE
游客不能搜fid语法啊，但是非付费注册用户能搜，能不能加上登录账户功能？

### ISSUE THREAD

**Issue by randomshit699** [Cl0udG0d/Fofa-hack#62]

**Comment by Cl0udG0d** [comment]
下一个版本会支持

**Comment by Cl0udG0d** [comment]
使用 [v2.4.12](https://github.com/Cl0udG0d/Fofa-hack/releases/tag/v2.4.12) 版本

> fofa-hack.exe --keyword thinkphp --endcount 500 --authorization your_authorization

使用 --authorization 输入自己非付费注册用户的 authorization ，可以实现频率10/次的爬取

**Comment by Cl0udG0d** [comment]
authorization的位置在

![image](https://github.com/Cl0udG0d/Fofa-hack/assets/45556496/f422b20f-ac40-4a6d-9430-b36d4b5e3992)

登录状态下使用F12，翻页的时候可以看到网络请求里面存在，header
