### ISSUE TITLE
能否增加一个参数用于计算icon_hash

### ISSUE THREAD

**Issue by Lyxxn** [Cl0udG0d/Fofa-hack#64]
增加一个--icon参数
可以计算指定本地icon文件的hash
也可以计算网站在线的ico url的hash
如果计算后可以自动作为keyword搜索就更好了

**Comment by Cl0udG0d** [comment]
下个版本

**Comment by Cl0udG0d** [comment]
使用 [v2.3.14](https://github.com/Cl0udG0d/Fofa-hack/releases/tag/v2.4.13)

**Comment by Cl0udG0d** [comment]
示例

指定本地文件 
> --iconfile ./favicon32.ico 

指定网址
> --iconurl https://g.csdnimg.cn/static/logo/favicon32.ico 


![image](https://github.com/Cl0udG0d/Fofa-hack/assets/45556496/e770b2bc-b77d-4ee6-b2a5-2c3c9af2b82d)

**Comment by Lyxxn** [comment]
谢谢作者大大
