### ISSUE TITLE
Error  error:'NoneType' object has no attribute 'text'

### ISSUE THREAD

**Issue by lolminerxmrig** [Cl0udG0d/Fofa-hack#65]
Hi
plz help me fixed Error :

![image](https://github.com/Cl0udG0d/Fofa-hack/assets/108659226/9733c60d-373e-4118-a6ea-553927c42af2)

**Comment by Cl0udG0d** [comment]
use [v2.3.14](https://github.com/Cl0udG0d/Fofa-hack/releases/tag/v2.4.13)

**Comment by Cl0udG0d** [comment]
> I had the same problem, but I have already solved it.
> 
> tookit/sign.py `size = 10 if config.AUTHORIZATION else 50`
> 
> Just change "size 50" to "size 20" in the getUrl method and you can solve it

Yes, FOFA further limits the number of accesses

**Comment by lolminerxmrig** [comment]
![image](https://github.com/Cl0udG0d/Fofa-hack/assets/108659226/5c4e1803-0d19-4143-b70b-c159bc0984e1)

**Comment by Cl0udG0d** [comment]
Do you need to log in to query your keywords

**Comment by lolminerxmrig** [comment]
No

**Comment by Cl0udG0d** [comment]
You can send me the keywords after desensitization

**Comment by lolminerxmrig** [comment]
can send telegram id?

**Comment by Cl0udG0d** [comment]
I don't use TG

**Comment by lolminerxmrig** [comment]
app="WSO2-Carbon-Server"

**Comment by Cl0udG0d** [comment]
![image](https://github.com/Cl0udG0d/Fofa-hack/assets/45556496/37d5b576-1c4e-49d1-90b3-fc61a1b9499a)

**Comment by lolminerxmrig** [comment]
![image](https://github.com/Cl0udG0d/Fofa-hack/assets/108659226/419bb385-d583-43ef-9b51-b0f0efe78afc)

**Comment by lolminerxmrig** [comment]
"screenconnect"
"WSO2-Carbon-Server"

**Comment by lolminerxmrig** [comment]
![image](https://github.com/Cl0udG0d/Fofa-hack/assets/108659226/1cb0b95d-1b83-4d34-a2df-a57ec471fb33)

**Comment by Cl0udG0d** [comment]
because the product following the syntax of the app needs to be included in the FOFA when needed

**Comment by Cl0udG0d** [comment]
When you search on the webpage yourself, you haven't added the **app=** field either

**Comment by lolminerxmrig** [comment]
> When you search on the webpage yourself, you haven't added the **app=** field either

![image](https://github.com/Cl0udG0d/Fofa-hack/assets/108659226/24b3a243-0c1e-4ee1-ba19-bd3cbc228ac9)

can help faster scan and full 120K save.

**Comment by lolminerxmrig** [comment]
can add code faster scan?

**Comment by Cl0udG0d** [comment]
can you post this website address

my use of the following website address is invalid

https://fofa.info/result?qbase64=YXBwPSJXU08yLUNhcmJvbi1TZXJ2ZXIi

![image](https://github.com/Cl0udG0d/Fofa-hack/assets/45556496/15333d8e-b983-429f-acf7-e57b7040ab8a)

I suspect it's a regional issue

**Comment by Cl0udG0d** [comment]
> > When you search on the webpage yourself, you haven't added the **app=** field either
> 
> ![image](https://private-user-images.githubusercontent.com/108659226/311194081-24b3a243-0c1e-4ee1-ba19-bd3cbc228ac9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxMjY2NDAsIm5iZiI6MTcxMDEyNjM0MCwicGF0aCI6Ii8xMDg2NTkyMjYvMzExMTk0MDgxLTI0YjNhMjQzLTBjMWUtNGVlMS1iYTE5LWJkM2NiYzIyOGFjOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMVQwMzA1NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MzRhNjU4ZmMzMjAyZDk5ZTBkMzkzMWIzOTYxYzE2YjRiYTRmNWI3NmQzMjVkMTMyNzVkYTY3MGRlOWVjMjlkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NO__T2Aoew2NqdKiAkq376dqXDyZjGPL_TkBix_va7E)
> 
> can help faster scan and full 120K save.

this website
