### ISSUE TITLE
 error:list index out of range

### ISSUE THREAD

**Issue by lolminerxmrig** [Cl0udG0d/Fofa-hack#66]
hi
fofa.py -k "app='JET_BRAINS-TeamCity' && country='US'" --e 25000 -o teamcity.txt

![image](https://github.com/Cl0udG0d/Fofa-hack/assets/108659226/1a95e1d5-ed93-4d5e-aa2b-1f33fc3cced4)

https://fofa.info/result?qbase64=YXBwPSJKRVRfQlJBSU5TLVRlYW1DaXR5IiAmJiBjb3VudHJ5PSJVUyI%3D

**Comment by Cl0udG0d** [comment]
I have visited the website you sent and there are no search results

![image](https://github.com/Cl0udG0d/Fofa-hack/assets/45556496/a3fc9151-eb29-4631-8005-3c09f7b0c5cd)

**Comment by lolminerxmrig** [comment]
but me see data:

![image](https://github.com/Cl0udG0d/Fofa-hack/assets/108659226/5a734ca7-1e63-46db-ac50-da750d0767c6)

**Comment by Cl0udG0d** [comment]
the next version will solve this problem

**Comment by Cl0udG0d** [comment]
I feel very puzzled. Previously, I couldn't access this address on the page, but now I can access it normally again. Fofa back can also obtain results normally, but I haven't made any changes to the content

https://fofa.info/result?qbase64=YXBwPSJKRVRfQlJBSU5TLVRlYW1DaXR5IiAmJiBjb3VudHJ5PSJVUyI%3D

**Comment by Cl0udG0d** [comment]
![image](https://github.com/Cl0udG0d/Fofa-hack/assets/45556496/16b1a7ca-3bdc-431b-bc4b-351044b6c5b3)

**Comment by Cl0udG0d** [comment]
这是扫描的结果

> fofa-hack_win_amd64.exe -k "app='JET_BRAINS-TeamCity' && country='US'"

![image](https://github.com/Cl0udG0d/Fofa-hack/assets/45556496/2a342086-a575-49d8-943a-f1b95e63aa41)
