### ISSUE TITLE
支持Mac系统吗

### ISSUE THREAD

**Issue by m4ra7h0n** [Cl0udG0d/Fofa-hack#67]
<img width="378" alt="image" src="https://github.com/Cl0udG0d/Fofa-hack/assets/71647398/5597693a-a141-481c-997a-ce69ab0e749b">

**Comment by Cl0udG0d** [comment]
目前不支持，因为我没有Mac~

**Comment by m4ra7h0n** [comment]
> 目前不支持，因为我没有Mac~

好的
