### ISSUE TITLE
使用访问api访问报错

### ISSUE THREAD

**Issue by m4ra7h0n** [Cl0udG0d/Fofa-hack#68]
<img width="796" alt="image" src="https://github.com/Cl0udG0d/Fofa-hack/assets/71647398/efa3d0b3-42b8-4f93-8c78-28846ab151f1">

所以是不是也需要加入登录后的session之类的

**Comment by Cl0udG0d** [comment]
不需要 你git pull 更新一下本地的代码

**Comment by Cl0udG0d** [comment]
![image](https://github.com/Cl0udG0d/Fofa-hack/assets/45556496/7bfebdb1-a657-47d8-9345-fb227da8751c)

**Comment by Cl0udG0d** [comment]
这个问题解决了吗 解决了的话我就关闭issue了
