### ISSUE TITLE
能否获取指定某个日期后的内容，而不是获取写定的数量

### ISSUE THREAD

**Issue by jiemo9527** [Cl0udG0d/Fofa-hack#69]
如题

**Comment by Cl0udG0d** [comment]
你可以指定某个日期为关键字 比如

> app="ThinkPHP" && before="2023-12-01"

使用fofa-hack为

> fofa-hack_win_amd64.exe -k "app='ThinkPHP' && before='2023-12-01'"

**Comment by Cl0udG0d** [comment]
![image](https://github.com/Cl0udG0d/Fofa-hack/assets/45556496/c1431411-5090-4266-89e3-07f09b2959a3)
