### ISSUE TITLE
 --

### ISSUE THREAD

**Issue by what127374** [Cl0udG0d/Fofa-hack#70]

**Comment by Cl0udG0d** [comment]
技术上是完全可以实现的，但是我觉得现在没有必要使用这个方式，原因如下：
+ 每次搜索都会进行时间辍的过滤，如果添加筛选条件，其实对于每次搜索都会存在两个变量
+ 扫描结束之后会对所有的结果进行一次去重过滤

but,,,,我觉得这是一个很有趣的点子,即便时间辍的方式被禁止,这种筛选条件的方式也可以不断的获取数据，如下
![image](https://github.com/Cl0udG0d/Fofa-hack/assets/45556496/be7d59bd-4dc6-4818-b253-db2df7cfb17b)
