### ISSUE TITLE
banned by fofa , what should i do?

### ISSUE THREAD

**Issue by RHYru9** [Cl0udG0d/Fofa-hack#72]
![Screenshot (14)](https://github.com/Cl0udG0d/Fofa-hack/assets/164749781/e820c0e2-8192-4546-ad3c-49649405a1f6)

**Comment by lolminerxmrig** [comment]
me too

![image](https://github.com/Cl0udG0d/Fofa-hack/assets/108659226/009cc843-051c-40fd-a0aa-0372e9168a41)

**Comment by Cl0udG0d** [comment]
It's strange that it's normal on my computer, and I can't reproduce this problem. I guess it's because of the region you're running in. What is your country?
![image](https://github.com/Cl0udG0d/Fofa-hack/assets/45556496/1fdbf373-1459-4c37-8a6a-a5b27fd48295)

**Comment by lolminerxmrig** [comment]
USA , England

**Comment by Cl0udG0d** [comment]
> I think it would be great to add an option, proxy list... like socks5, http, and socks4 --proxy-list, hopefully there will be an update, and special thanks to admin for making fofa-hack.

proxy can be used for access

use https://github.com/Cl0udG0d/Fofa-hack/releases/tag/v2.4.14

ex:

The agent here is a publicly available socks5 agent that I found

> fofa-hack.exe -k index --proxy 18.178.209.57:5555 --proxy-type socks5

![image](https://github.com/Cl0udG0d/Fofa-hack/assets/45556496/d164cd60-e668-4906-a98a-68db27ebaded)


and its address is in Japan

![image](https://github.com/Cl0udG0d/Fofa-hack/assets/45556496/b2cfe09d-70e9-473b-9ce7-44e5bae32f44)

**Comment by JackSparrowhk** [comment]
> > I think it would be great to add an option, proxy list... like socks5, http, and socks4 --proxy-list, hopefully there will be an update, and special thanks to admin for making fofa-hack.
> 
> proxy can be used for access
> 
> use https://github.com/Cl0udG0d/Fofa-hack/releases/tag/v2.4.14
> 
> ex:
> 
> The agent here is a publicly available socks5 agent that I found
> 
> > fofa-hack.exe -k index --proxy 18.178.209.57:5555 --proxy-type socks5
> 
> ![image](https://private-user-images.githubusercontent.com/45556496/319088743-d164cd60-e668-4906-a98a-68db27ebaded.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxNDIxMTMsIm5iZiI6MTcxMjE0MTgxMywicGF0aCI6Ii80NTU1NjQ5Ni8zMTkwODg3NDMtZDE2NGNkNjAtZTY2OC00OTA2LWE5OGEtNjhkYjI3ZWJhZGVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDEwNTY1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2ZmU1OWNlNWNmMzFkNjk3MTE0NTQ1NGI3NTg2MmY0NjZkYzZiYTNkOGYyOGFhNTQ2ZGY1MmUwNmQ0MzU0NTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M6nsKEFWkojgGC2cVEbcxjeQTy1myXjL974R6f-8Hos)
> 
> and its address is in Japan
> 
> ![image](https://private-user-images.githubusercontent.com/45556496/319088945-b2cfe09d-70e9-473b-9ce7-44e5bae32f44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxNDIxMTMsIm5iZiI6MTcxMjE0MTgxMywicGF0aCI6Ii80NTU1NjQ5Ni8zMTkwODg5NDUtYjJjZmUwOWQtNzBlOS00NzNiLTljZTctNDRlNWJhZTMyZjQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDEwNTY1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyNmU5N2VjODNhNjE4MjZiMmUzYzExYThlZWJmYjgzOTc4ZmVjM2VjNzBmOGNjYjJlODljNTM0NDkyYzg3ODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w-zo8Jxuz2gCfwGfTz4nNW-W7MoszyVmXctdNGtkZxY)

有用

**Comment by lolminerxmrig** [comment]
![image](https://github.com/Cl0udG0d/Fofa-hack/assets/108659226/bdd7b4fa-2490-4ba4-b0e0-9d99d269f9e9)
Why?

**Comment by Cl0udG0d** [comment]
the proxies given are only examples, you will need to use your own proxies for actual use.

here 18.178.209.57:5555 is a free proxy address I was looking for

You can find proxies on, for example, the following websites, but you need to verify the availability yourself

+ https://www.kuaidaili.com/free/
+ https://github.com/Python3WebSpider/ProxyPool
+ .....
