### ISSUE TITLE
--proxy set ?

### ISSUE THREAD

**Issue by lolminerxmrig** [Cl0udG0d/Fofa-hack#73]
Hi.
Not work : 

python3 fofa.py --keyword body="AAAAAa" --endcount 30000 -o aaa.txt --authorization AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA --proxy '15.156.24.206:3128'

**Comment by Cl0udG0d** [comment]
not work?

Send out a screenshot of the operation to take a look

**Comment by Cl0udG0d** [comment]
proxy can be used for access

use https://github.com/Cl0udG0d/Fofa-hack/releases/tag/v2.4.14

ex:

The agent here is a publicly available socks5 agent that I found

> fofa-hack.exe -k index --proxy 18.178.209.57:5555 --proxy-type socks5

![image](https://github.com/Cl0udG0d/Fofa-hack/assets/45556496/d164cd60-e668-4906-a98a-68db27ebaded)


and its address is in Japan

![image](https://github.com/Cl0udG0d/Fofa-hack/assets/45556496/b2cfe09d-70e9-473b-9ce7-44e5bae32f44)

**Comment by lolminerxmrig** [comment]
plz add random proxy select and load proxy.txt
thanks.

**Comment by Cl0udG0d** [comment]
> plz add random proxy select and load proxy.txt
> thanks.

No, I don't think this feature is necessary for Fofa hack

**Comment by lolminerxmrig** [comment]
> > plz add random proxy select and load proxy.txt
> > thanks.
> 
> No, I don't think this feature is necessary for Fofa hack
yes very need for fofa-hack, block proxy try next proxy try next proxy.

**Comment by qq54288** [comment]
> > > plz add random proxy select and load proxy.txt
> > > thanks.
> > 
> > 
> > No, I don't think this feature is necessary for Fofa hack
> > yes very need for fofa-hack, block proxy try next proxy try next proxy.

You can build tunnel agents.
