### ISSUE TITLE
按日期每日只能下载20条数据吗？

### ISSUE THREAD

**Issue by Tianer1123** [Cl0udG0d/Fofa-hack#76]
大佬，非常感谢您这个软件。

我在使用得时候看到如果使用 --authorization 参数，好像会按照日期，每个日期下载10条数据。

fofa会员每次查询会消耗1次查询次数，普通会员1次查询好像最多可以查看50条数据，可以修改每次查询一页得数据量么？

如果按照日期一次查询10条或者50条数据，如果资产在当天很多，会不会漏数据？

**Comment by Cl0udG0d** [comment]
关于最后一个问题
> 如果按照日期一次查询10条或者50条数据，如果资产在当天很多，会不会漏数据？

会的，如果当天数据很多 是会存在漏数据的情况，但是鱼和熊掌不可兼得，目前来看只能这样

**Comment by Cl0udG0d** [comment]
> 大佬，非常感谢您这个软件。
> 
> 我在使用得时候看到如果使用 --authorization 参数，好像会按照日期，每个日期下载10条数据。
> 
> fofa会员每次查询会消耗1次查询次数，普通会员1次查询好像最多可以查看50条数据，可以修改每次查询一页得数据量么？
> 
> 如果按照日期一次查询10条或者50条数据，如果资产在当天很多，会不会漏数据？

其实我理解这里的需求是 普通会员的查询自动切换成50条每页，这个会在下个版本更新

**Comment by Tianer1123** [comment]
> > 大佬，非常感谢您这个软件。
> > 我在使用得时候看到如果使用 --authorization 参数，好像会按照日期，每个日期下载10条数据。
> > fofa会员每次查询会消耗1次查询次数，普通会员1次查询好像最多可以查看50条数据，可以修改每次查询一页得数据量么？
> > 如果按照日期一次查询10条或者50条数据，如果资产在当天很多，会不会漏数据？
> 
> 其实我理解这里的需求是 普通会员的查询自动切换成50条每页，这个会在下个版本更新

是的，普通会员每页50条，我是在url连接中测试出来得，但是否为50条我还不太确定。
`https://fofa.info/result?qbase64=InRoaW5rcGhwIg%3D%3D&page=1&page_size=50`
![image](https://github.com/Cl0udG0d/Fofa-hack/assets/7273262/a3a5fbb4-6eea-4023-8b29-e9c21f2d380d)

**Comment by Cl0udG0d** [comment]
> > > 大佬，非常感谢您这个软件。
> > > 我在使用得时候看到如果使用 --authorization 参数，好像会按照日期，每个日期下载10条数据。
> > > fofa会员每次查询会消耗1次查询次数，普通会员1次查询好像最多可以查看50条数据，可以修改每次查询一页得数据量么？
> > > 如果按照日期一次查询10条或者50条数据，如果资产在当天很多，会不会漏数据？
> > 
> > 
> > 其实我理解这里的需求是 普通会员的查询自动切换成50条每页，这个会在下个版本更新
> 
> 是的，普通会员每页50条，我是在url连接中测试出来得，但是否为50条我还不太确定。 `https://fofa.info/result?qbase64=InRoaW5rcGhwIg%3D%3D&page=1&page_size=50` ![image](https://private-user-images.githubusercontent.com/7273262/323874774-a3a5fbb4-6eea-4023-8b29-e9c21f2d380d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MTM4NDMsIm5iZiI6MTcxMzUxMzU0MywicGF0aCI6Ii83MjczMjYyLzMyMzg3NDc3NC1hM2E1ZmJiNC02ZWVhLTQwMjMtOGIyOS1lOWMyMWYyZDM4MGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTlUMDc1OTAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjI5YzRjMzg4OWIyODVlODZiZjBlYmViNzQ4ZmI2MWQ4MmYyOTljYzRhMDAxOGNjMzNjMDU1ZWIxMmU4ZmQ5NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.SFRR7z1-DuGHkjVb3m5mre_fl-aVTWRCdFMCn9iJY6s)

是的 普通会员一次可以获取到50条数据，我之前的代码里面限制了10条，已经在新版本里面改过来了

可以试试这个 加--authorization参数 [fofa hack v2.4.15 ](https://github.com/Cl0udG0d/Fofa-hack/releases/tag/v2.4.15)

**Comment by jiemo9527** [comment]
能不能拿到时分秒 lastupdatetime或者mtime，否则每天只能50条

**Comment by Cl0udG0d** [comment]
> 能不能拿到时分秒 lastupdatetime或者mtime，否则每天只能50条

关于这个问题 

为什么没有加这个参数来进行过滤 是因为fofa 的查询API限制了这个参数只能专业版才可以获取 所以作为游客的我们是不能用这个进行查询的

![image](https://github.com/user-attachments/assets/aa324e80-c8be-4bab-9534-d9dad3d6306b)

**Comment by jiemo9527** [comment]
mtime是可以拿到的；但是现在有个更简单的处理方式。修改before的逻辑 before=“2024-08-01 23:00:00”则依次向前搜素每个小时（before22点、21点....），我手动查是可以过渡的，只需要加上时分秒的处理逻辑，因为fofa是每小时搜集一次数据

**Comment by Cl0udG0d** [comment]
我不确定这种方式会不会数据的重复度很高 :)

下一个版本添加这个功能呢，作为一个可选项让用户使用，正常使用的时候还是默认按天获取

**Comment by jiemo9527** [comment]
> 我不确定这种方式会不会数据的重复度很高 :)
> 
> 下一个版本添加这个功能呢，作为一个可选项让用户使用，正常使用的时候还是默认按天获取

只能说获得的数据从千分之一，变成了百分之一的可能。每小时的数据之间不重复 这点我使用专业版验证过了，
在百万条的数据中，重复的可能是历史数据 约为万分之30-300左右

**Comment by Cl0udG0d** [comment]
使用一下最新代码呢

> python fofa.py -k index -e 100  --time-type hour

![image](https://github.com/user-attachments/assets/6b850b78-5c52-4fc2-92a5-e51c444cdc46)

默认还是按照天的，可以自定义选择小时

**Comment by jiemo9527** [comment]
> 使用一下最新代码呢
> 
> > python fofa.py -k index -e 100  --time-type hour
> 
> ![image](https://private-user-images.githubusercontent.com/45556496/369679946-6b850b78-5c52-4fc2-92a5-e51c444cdc46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwNTk4ODMsIm5iZiI6MTcyNzA1OTU4MywicGF0aCI6Ii80NTU1NjQ5Ni8zNjk2Nzk5NDYtNmI4NTBiNzgtNWM1Mi00ZmMyLTkyYTUtZTUxYzQ0NGNkYzQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIzVDAyNDYyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2ZjkwYThmZWYwMDgwNmU1OTM1N2U4M2EyYTQ1YzcyNWYzN2ZkZGZjZTdmYzg1Mjc0ZGZlM2VjZTdkMjFhNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Si1w3uaRCElwBRtn3aBUMhhc50eCMBVg1_HPc9SQRDo)
> 
> 默认还是按照天的，可以自定义选择小时

可以的 数据量足够时，每天600条
