### ISSUE TITLE
多个authorization

### ISSUE THREAD

**Issue by Tianer1123** [Cl0udG0d/Fofa-hack#77]
比如我有3个账号，authorization是否可以从文件中读取，并做成列表。

这样当1页50条数据，300次额度用完后，使用新得authorization来获取数据。从而增加下载数量。

在不使用authorization时，下载了几次数据后就似乎就被ban掉，无法使用了。

不知道使用authorization是否会更稳定些？

**Comment by Cl0udG0d** [comment]
读取authorization可以后续作为一个TODO项，因为authorization额度是否用完，也是需要每次去检测和判断的

不使用authorization的时候，被ban掉一般是因为一直在请求数据，fofa会有一些反爬措施，可以考虑使用代理参数 --proxy

**Comment by Tianer1123** [comment]
> 读取authorization可以后续作为一个TODO项，因为authorization额度是否用完，也是需要每次去检测和判断的
> 
> 不使用authorization的时候，被ban掉一般是因为一直在请求数据，fofa会有一些反爬措施，可以考虑使用代理参数 --proxy

好的，谢谢了!!!

**Comment by Cl0udG0d** [comment]
最新版本[2.4.16](https://github.com/Cl0udG0d/Fofa-hack/releases/tag/v2.4.16)已经新增了多个authorization的选项，从txt文件中进行读取即可，示例使用

> fofa-hack_win_amd64.exe -k index --authorization-file au.txt

![image](https://github.com/Cl0udG0d/Fofa-hack/assets/45556496/15a6fdbd-8b8f-4fb9-8f90-c55793425d3b)
