### ISSUE TITLE
早上还正常的，晚上就这样了，有点奇怪

### ISSUE THREAD

**Issue by Another-YY** [Cl0udG0d/Fofa-hack#79]
E:\桌面\WA-WJ\fofa\fofa-hack>fofa-hack_win_amd64.exe -k "Druid && country=\"US\""

             ____  ____  ____  ____
            | ===|/ () \| ===|/ () \
            |__|  \____/|__| /__/\__\
                 _   _   ____   ____  __  __
                | |_| | / () \ / (__`|  |/  /
                |_| |_|/__/\__\\____)|__|\__\ V2.4.15

                公众号: 黑糖安全

[*] LEVEL = 1 , 初始化成功
[*] 爬取延时: 3s
[*] 爬取关键字: Druid && country="US"
[*] 爬取结束数量: 100
[*] 输出格式为: txt
[*] 存储文件名: fofaHack.txt
[*] 是否开启关键字fuzz: False
[*] 是否开启代理: False
[*] 读取文件: None

[*] 开始运行
[*] 爬取页面为:https://fofa.info/result?qbase64=RHJ1aWQgJiYgY291bnRyeT0iVVMi
[-] error:list index out of range
[-] perhaps there is a problem with your network or your area has been officially banned by Fofa, so the program exits

E:\桌面\WA-WJ\fofa\fofa-hack>fofa-hack_win_amd64.exe -k "Druid && country=\"US\""

             ____  ____  ____  ____
            | ===|/ () \| ===|/ () \
            |__|  \____/|__| /__/\__\
                 _   _   ____   ____  __  __
                | |_| | / () \ / (__`|  |/  /
                |_| |_|/__/\__\\____)|__|\__\ V2.4.15

                公众号: 黑糖安全

[*] LEVEL = 1 , 初始化成功
[*] 爬取延时: 3s
[*] 爬取关键字: Druid && country="US"
[*] 爬取结束数量: 100
[*] 输出格式为: txt
[*] 存储文件名: fofaHack.txt
[*] 是否开启关键字fuzz: False
[*] 是否开启代理: False
[*] 读取文件: None

[*] 开始运行
[*] 爬取页面为:https://fofa.info/result?qbase64=RHJ1aWQgJiYgY291bnRyeT0iVVMi
[*] 存在数量:139,881
now search key: Druid && country="US"
string indices must be integers
[-] error:'NoneType' object has no attribute 'text'
[-] 第1次尝试获取页面URL
string indices must be integers
[-] error:'NoneType' object has no attribute 'text'
[-] 第2次尝试获取页面URL
string indices must be integers
[-] error:'NoneType' object has no attribute 'text'
[-] 第3次尝试获取页面URL
[-] FOFA资源获取重试超过最大次数,程序退出
[-] error:[Errno 2] No such file or directory: 'fofaHack.txt'

**Comment by Cl0udG0d** [comment]
因为现在fofa对游客从API请求进行了限制，用fofa-hack的用户都会走这个API

你访问的地址是 https://fofa.info/result?qbase64=RHJ1aWQgJiYgY291bnRyeT0iVVMi

API的对应地址是（当然这个时间戳可能过段时间会更新） https://api.fofa.info/v1/search?qbase64=RHJ1aWQgJiYgY291bnRyeT0iVVMi&full=false&page=1&size=20&ts=1716132492729&sign=JW8hmACzlHfMBQ4F%2B8BAnVMDxpoXgc6aXky3oKXh4z38DREt8YAE0HnUX8BwFgBKH4Dm5vXLf6H1vWhwQC3wzasjZei%2BQncI5becaZxj1IF9umDbOIuUNgx7xw7pihbtLerzYaiSueeF4xTphFSmJwybytwcBmd9FUwrAelNw8A6FsFEwa8ayo4LAtBAx20LOBYf9qNmMcZETWMlDPHyAv/KGxAdk/HrYdYO7Y72%2B6tLDB7cDLzyE60TNf61ZR/ZX%2B6yqvW2amVTtVPqdnVqDS%2BX8QukOr6T2tZMwjjN6iGgiqYx42zQO4lElJukaaD9PEvHH0wVw8An4/YwZBwJDA%3D%3D&app_id=9e9fb94330d97833acfbc041ee1a76793f1bc691

访问之后页面会显示
![image](https://github.com/Cl0udG0d/Fofa-hack/assets/45556496/4b2da0c2-76d1-42f6-88e3-5bd0dedaf487)

所以出现了早上还可以 但是晚上就不行了的情况

**Comment by Another-YY** [comment]
噢噢，等明天正常刷新就可以了是吧，了解了，感谢大佬解惑

**Comment by Cl0udG0d** [comment]
今天又试了一下 感觉还有一个原因可能是游客状态请求API的速率太快导致的，我使用 --timesleep 10之后效果稍微好一点
![image](https://github.com/Cl0udG0d/Fofa-hack/assets/45556496/6e357f84-63e2-4ac6-923b-2abbe60e0717)

总的来说还是这个接口进行限制了，所以没有以前那么好用了

**Comment by Cl0udG0d** [comment]
最新版本[2.4.16](https://github.com/Cl0udG0d/Fofa-hack/releases/tag/v2.4.16)已经新增了多个authorization的选项，可以把自己注册用户的authorization放置到txt中，示例使用

> fofa-hack_win_amd64.exe -k index --authorization-file au.txt

![image](https://github.com/Cl0udG0d/Fofa-hack/assets/45556496/15a6fdbd-8b8f-4fb9-8f90-c55793425d3b)
