### ISSUE TITLE
共享 authorization 

### ISSUE THREAD

**Issue by Cl0udG0d** [Cl0udG0d/Fofa-hack#80]
> 如果大家有注册的多余没用的账号,也可以把authorization提交到 issue里面来实现共享
>
> (当然 是指普通用户的

如果这部分比较多的话 我会将共享的authorization集成到Fofa-hack中

**Comment by Cl0udG0d** [comment]
authorization的位置在

![image](https://github.com/Cl0udG0d/Fofa-hack/assets/45556496/f422b20f-ac40-4a6d-9430-b36d4b5e3992)

登录状态下使用F12，翻页的时候可以看到网络请求里面存在authorization

**Comment by Cl0udG0d** [comment]
例如我已经在项目主程序中上传了两个测试账户的authorization

https://github.com/Cl0udG0d/Fofa-hack/blob/main/au.txt

可以直接使用这个文件测试  --authorization-file au.txt 参数

单个账户的月查询额度是 3000，如果你也有不暴露个人信息的测试fofa账户请提交authorization在此处

**Comment by chendi2** [comment]
更新一下获取token的方式：<img width="719" alt="Snipaste_2024-05-22_22-46-43" src="https://github.com/Cl0udG0d/Fofa-hack/assets/55273217/d53c425d-b509-4ea5-8c39-76fcd49e7b96">

**Comment by ailx1101** [comment]
请问这个authorization不会过期吗

**Comment by Cl0udG0d** [comment]
我宣布 我 是 傻 逼 ~ :)

忘记这玩意是会过期了 ， 刚才试了一下确实过期了 

看来注册用户还是得用 API  KEY 可以实现自己控制是否过期  

下一版本更新加入API KEY的内容

**Comment by lolminerxmrig** [comment]
![image](https://github.com/user-attachments/assets/4ae5b994-61ba-4b56-9d08-e93d535d377b)

**Comment by lolminerxmrig** [comment]
![image](https://github.com/user-attachments/assets/afe15b81-8ff7-440b-a675-e0274fafa1bc)
can help me fixed Error
