### ISSUE TITLE
无法添加多个查询条件

### ISSUE THREAD

**Issue by MCyudix** [Cl0udG0d/Fofa-hack#81]
比如 app="" && port=""

**Comment by qq54288** [comment]
可以啊例如
-k "app='xx' && port='xx'"
查询的时候会替换成双引号应该是大佬写在代码里了

**Comment by MCyudix** [comment]
没事了引号加错了（）大佬怎么回复的这么快

**Comment by Clarence-G** [comment]
@Cl0udG0d 
大佬，我崩溃了，我的查询条件是：body='{"code":200,"message":"DeepL Free API, Developed by sjlleo and missuo. Go to /translate with POST. http://github.com/OwO-Network/DeepLX"}' 在网页搜索框里面是对的，用命令行工具每次处理的都不对，查不到东西，我希望能完全不处理字符串，只传递原始字符串可以吗。

**Comment by Cl0udG0d** [comment]
使用 --base 参数 ，如下

> python fofa.py --base Ym9keT0neyJjb2RlIjoyMDAsIm1lc3NhZ2UiOiJEZWVwTCBGcmVlIEFQSSwgRGV2ZWxvcGVkIGJ5IHNqbGxlbyBhbmQgbWlzc3VvLiBHbyB0byAvdHJhbnNsYXRlIHdpdGggUE9TVC4gaHR0cDovL2dpdGh1Yi5jb20vT3dPLU5ldHdvcmsvRGVlcExYIn0nIA== -e 100

如图

![image](https://github.com/Cl0udG0d/Fofa-hack/assets/45556496/fc49922e-67c2-4db6-84ee-8c0b8eba2135)

**Comment by Cl0udG0d** [comment]
以base64的形式传入原始字符串 避免分割符号导致输入错误

> --base BASE, -b BASE  以base64的形式输入关键字 -b InRoaW5rcGhwIg==
