### ISSUE TITLE
api调用的问题

### ISSUE THREAD

**Issue by PSH-1997** [Cl0udG0d/Fofa-hack#83]
![image](https://github.com/user-attachments/assets/380a3a91-c489-4433-996b-76a4a22f862b)

**Comment by Cl0udG0d** [comment]
该报错是因为fofa官方修改了游客通过api获取的数量，我晚点更新一下pip包

**Comment by Cl0udG0d** [comment]
已更新，请使用fofa-hack 0.0.2版本的pip包 https://pypi.org/project/fofa-hack/

**Comment by PSH-1997** [comment]
已解决，感谢作者
