### ISSUE TITLE
输出为json -l 2 3 时报错 之前说解决这个问题了 ，但是还存在 版本是2.4.16

### ISSUE THREAD

**Issue by PSH-1997** [Cl0udG0d/Fofa-hack#86]
![image](https://github.com/user-attachments/assets/89700472-dc84-4c32-aa5b-f779be3d3ed1)
![image](https://github.com/user-attachments/assets/1f592a02-9f63-4651-9cdb-4163733d5636)

**Comment by Cl0udG0d** [comment]
测试后确实存在该问题 下一个版本修复~

**Comment by Cl0udG0d** [comment]
在版本 (v2.5.1)[https://github.com/Cl0udG0d/Fofa-hack/releases/tag/v2.5.1] 已解决该问题

**Comment by Cl0udG0d** [comment]
![image](https://github.com/user-attachments/assets/420a0a9d-ef18-442a-b1d0-793f166d07e6)
