### ISSUE TITLE
希望支持正则表达式过滤

### ISSUE THREAD

**Issue by Arjen10** [Cl0udG0d/Fofa-hack#87]
现在爬取下来的地址是http url，可不可以增加正则表达式参数来实现自定义过滤获得 ip 地址

**Comment by Cl0udG0d** [comment]
你是指像fofa接口一样 能够导出http url对应的ip地址出来吗

**Comment by Arjen10** [comment]
> 你是指像fofa接口一样 能够导出http url对应的ip地址出来吗

对，比如说我可以自己写个正则去匹配我想要的

**Comment by Cl0udG0d** [comment]
我现在是用xpath去解析页面元素获取的结果
![image](https://github.com/user-attachments/assets/06d2cfa6-442c-4287-b7f8-61abb76b7e38)
如果我没有理解错误的话，就是说添加一个输入正则表达式参数的地方，这样可以导出你自己想要规则的结果对吧

这个是可以的，下一个版本添加这个功能

**Comment by Arjen10** [comment]
> 我现在是用xpath去解析页面元素获取的结果 ![image](https://private-user-images.githubusercontent.com/45556496/361242010-06d2cfa6-442c-4287-b7f8-61abb76b7e38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2MzQ1NzYsIm5iZiI6MTcyNDYzNDI3NiwicGF0aCI6Ii80NTU1NjQ5Ni8zNjEyNDIwMTAtMDZkMmNmYTYtNDQyYy00Mjg3LWI3ZjgtNjFhYmI3NmI3ZTM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDAxMDQzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjODA5N2YyZmZjMmRkZjZlNGM1YWYwZGExMTk1OGI0ZjdhNGExMzFkMjU4ZjAyZjEyNmRhNzZiYjFkYTBhNWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SVLLtuT2Ook0Sl0G-RFANu2cX4wOa7j4-Zf3EXMF4EE) 如果我没有理解错误的话，就是说添加一个输入正则表达式参数的地方，这样可以导出你自己想要规则的结果对吧
> 
> 这个是可以的，下一个版本添加这个功能

期待

**Comment by Cl0udG0d** [comment]
因为fofa-hack可以调整输出的等级，即 --level ，当level 为3的时候可以下载所有的目标数据

例如 https://api.fofa.info/v1/search?qbase64=ImluZGV4Ig%3D%3D&full=false&page=1&size=20&ts=1726994633393&sign=Jfze4tdq4PDwIPYvwXDAI0L7WUXyHpCfNP8tqG9KY5gPMmIZzdcJDrRb3U1sXQaEJSENCqfl6yYYvSSjbuyAt04eZzZtoSsNXQol%2BWXoEYhX2BKTwtne13soXL7gxhMvx3tRkwaOewzK5XWixeK8z3OuoLHjdbfX4M7rd7TSfNTVWp%2BPi7olOXRUb6LUksX/S77mEYpggvSCrI0khOUeWdJPQ1QSLzJ9kfntk387QqQcq%2BfXCOsjVto0DW0njMZJaC6K7wdAuHK4ZDCKpTO0PYw/esvY8ol0YJavE4jzpH54Go/yaHgP4of9a3f9IgVEgSGHa/x9Dfma7gOlmsQ1gw%3D%3D&app_id=9e9fb94330d97833acfbc041ee1a76793f1bc691

![image](https://github.com/user-attachments/assets/9a527f80-3269-4805-8486-e65bc6230a00)

页面上展示的数据都会以API的形式返回给我们，当你使用参数

> python fofa.py -k index -e 10 -l 3

返回的数据就全部是上面可以看到的

所以我理解你想要获取数据的需求其实使用 level参数就可以解决
