### ISSUE TITLE
Error mmh3

### ISSUE THREAD

**Issue by lolminerxmrig** [Cl0udG0d/Fofa-hack#89]
Hi.
plz Help Me Fixed Error :

![image](https://github.com/user-attachments/assets/d8b16278-f883-4d29-9261-e78b3e84c798)

**Comment by lolminerxmrig** [comment]
python 3.1
os kali

**Comment by Cl0udG0d** [comment]
looks like your library wasn't found....

did you run with this device before?

I understand you can just download the binary.

**Comment by Cl0udG0d** [comment]
if you want to troubleshoot the error, you can try using the

```shell
pip list | grep mmh3
```

check if the third-party libraries are installed successfully
