### ISSUE TITLE
How to Search ?

### ISSUE THREAD

**Issue by lolminerxmrig** [Cl0udG0d/Fofa-hack#90]
Hi.
plz help me search :

(icon_hash="-829" || icon_hash="-1832" || icon_hash="43")

**Comment by fangyuan99** [comment]
`python fofa.py -k "icon_hash='-829' || icon_hash='-1832' || icon_hash='43'" -e 3000`

**Comment by Cl0udG0d** [comment]
> `python fofa.py -k "icon_hash='-829' || icon_hash='-1832' || icon_hash='43'" -e 3000`

感谢这位路过的靓仔

thank you to this handsome man who passed by

**Comment by Cl0udG0d** [comment]
Suddenly I realised that this keyword was wrong before   

if you 

> python fofa.py -k "icon_hash='-829' || icon_hash='-1832' || icon_hash='43'"

you get

> "icon_hash="-829" || icon_hash="-1832" || icon_hash="43""

https://fofa.info/result?qbase64=Imljb25faGFzaD0iLTgyOSIgfHwgaWNvbl9oYXNoPSItMTgzMiIgfHwgaWNvbl9oYXNoPSI0MyIi

**Comment by Cl0udG0d** [comment]
The reason for this is that fofa-hack has a problem when dealing with such complex input keywords

one correct answer is 

> python fofa.py --base aWNvbl9oYXNoPSItODI5IiB8fCBpY29uX2hhc2g9Ii0xODMyIiB8fCBpY29uX2hhc2g9IjQzIg==

But I don't see any results.

![image](https://github.com/user-attachments/assets/26b48b09-70e0-4b6f-8988-9cb0988d124d)

**Comment by lolminerxmrig** [comment]
fofa.py -k "icon_hash='-1275226814' || icon_hash='1927481616' || icon_hash='-1437701105' || icon_hash='111241152'" -e 9000000 -o 01.txt --authorization

![image](https://github.com/user-attachments/assets/ace4dad9-28ee-4ae7-aeea-556649de842a)
