### ISSUE TITLE
感谢作者分享，能不能打包arm32v7/Ubuntu可以执行的

### ISSUE THREAD

**Issue by wanqian6311** [Cl0udG0d/Fofa-hack#91]
我自己尝试打包，奈何功底不足，pip install cryptography lxml  这两个一直报错，折腾一下午没弄明白，还是来麻烦作者了，希望能添加arm32v7/Ubuntu可以执行的单文件，万分感谢！

**Comment by Cl0udG0d** [comment]
可以的，我更新arm32v7的二进制文件之后再回复这个评论，应该不会等待太久....

**Comment by Cl0udG0d** [comment]
> 我自己尝试打包，奈何功底不足，pip install cryptography lxml 这两个一直报错，折腾一下午没弄明白，还是来麻烦作者了，希望能添加arm32v7/Ubuntu可以执行的单文件，万分感谢！

我找了一圈没有找到这个系统的iso，要不你还是把报错信息发出来吧 我看看pip下载包这个问题容易解决不

**Comment by wanqian6311** [comment]
> > 我自己尝试打包，奈何功底不足，pip install cryptography lxml 这两个一直报错，折腾一下午没弄明白，还是来麻烦作者了，希望能添加arm32v7/Ubuntu可以执行的单文件，万分感谢！
> 
> 我找了一圈没有找到这个系统的iso，要不你还是把报错信息发出来吧 我看看pip下载包这个问题容易解决不

我用的docker拉取的镜像
```bash
docker pull arm32v7/ubuntu
docker run --rm --platform linux/arm/v7 -it arm32v7/ubuntu /bin/bash

```
下面是报错的信息，还有其他的报错，没找到记录
Collecting cryptography==43.0.0 (from -r requirements.txt (line 7))
  Using cached cryptography-43.0.0.tar.gz (686 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      
      Cargo, the Rust package manager, is not installed or is not on PATH.
      This package requires Rust and Cargo to compile extensions. Install it through
      the system's package manager or via https://rustup.rs/
      
      Checking for Rust toolchain....
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
(venv) root@b25d3008fdf9:/home/ubuntu/Fofa-hack#

**Comment by Cl0udG0d** [comment]
这个问题看起来可以参考 https://blog.csdn.net/dream6985/article/details/131246123 

使用下面的命令
> curl https://sh.rustup.rs -sSf | sh

执行完之后关闭终端再重新打开，重新执行pip

另外我这边也是使用docker pull 拉取的同一个image，不过我这个架构不对，所以运行不了....

**Comment by wanqian6311** [comment]
> 这个问题看起来可以参考 https://blog.csdn.net/dream6985/article/details/131246123
> 
> 使用下面的命令
> 
> > curl https://sh.rustup.rs -sSf | sh
> 
> 执行完之后关闭终端再重新打开，重新执行pip
> 
> 另外我这边也是使用docker pull 拉取的同一个image，不过我这个架构不对，所以运行不了....

又出了新的报错，由于字数限制，我把报错信息上传了https://github.com/wanqian6311/error/blob/main/README.md

Failed to build cryptography lxml                                      
ERROR: Could not build wheels for cryptography, lxml, which is required to install pyproject.toml-based projects                              
(myenv) root@c92534ec33cb:/home/ubuntu/Fofa-hack# 
就这两个安装不上.

我在论坛上悬赏了，也没人回复
提供源码，打包成arm32v7/ubuntu可以执行的单文件
https://www.52pojie.cn/thread-1966481-1-1.html
(出处: 吾爱破解论坛)

**Comment by Cl0udG0d** [comment]
我觉得这些问题是因为拉取的docker 镜像里面很多组件是不完全的，所以导致安装会出现问题

**Comment by wanqian6311** [comment]
> 我觉得这些问题是因为拉取的docker 镜像里面很多组件是不完全的，所以导致安装会出现问题

感谢帮助!!
我现在已经放弃打包了，我现在尝试在arm架构上拉取X86的docker镜像，然后在docker里运行

**Comment by Cl0udG0d** [comment]
好的~
